name: Reimann
favicon: null
layout_spectrum: 0.12762954295612872
typography_spectrum: 0.33279633964411914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.18381758988834918
  lightness: 0.8049232014454901
  saturation: 0.2882984976749867
  rhythmicContrast: 0.04347420786507428
purpose: []
